import "./globals.scss";
import type { Metadata } from "next";
import { Providers } from "@/store/provider";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import { Box, Container } from "@mui/material";
import HeaderBar from "@/components/ui/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <ThemeRegistry>
            <HeaderBar />
            <Box
              sx={{
                backgroundColor: "primary.main",
                minHeight: "100vh",
              }}
            >
              {children}
            </Box>
          </ThemeRegistry>
        </Providers>
      </body>
    </html>
  );
}
